# Write Kubernetes Deployment Script
apiVersion: apps/v1
kind: Deployment
metadata:
  name: book-catalog-deployment
  labels:
    app: book-catalog
spec:
  replicas: 3  # Number of desired pod replicas
  selector:
    matchLabels:
      app: book-catalog
  template:
    metadata:
      labels:
        app: book-catalog
    spec:
      containers:
      - name: book-catalog
        image: your-dockerhub-username/book-catalog:latest  # Replace with your actual Docker image
        ports:
        - containerPort: 8000
        env:
        - name: DATABASE_URL
          value: "postgresql://postgresql_week06_user:5DfKE50nVJ3Wsbdb2NpvzeHlLPjVJIIU@dpg-cr9f5b3v2p9s73b6nmhg-a.oregon-postgres.render.com/postgresql_week06"  # Update with your DB credentials and service name
        readinessProbe:
          httpGet:
            path: /books/
            port: 8000
          initialDelaySeconds: 10
          periodSeconds: 5
        livenessProbe:
          httpGet:
            path: /books/
            port: 8000
          initialDelaySeconds: 15
          periodSeconds: 20

        
